In [17]:
import numpy as np
a=np.array([[1,2],[3,4]])
print (a)
print (a.shape)
print (a.ndim)
print (a.size)
print (a.itemsize)
print (a.dtype)
b=np.array([[4,3],[2,1]])
print(a+b)
c=np.array([1,1])
tmp=a-np.tile(c,(2,1))
print(tmp)
print(2*a)

[[1 2]
 [3 4]]
(2, 2)
2
4
4
int32
[[5 5]
 [5 5]]
[[0 1]
 [2 3]]
[[2 4]
 [6 8]]


In [34]:
a=np.array([1,4,7])
b=np.array([2,5,8])
c=np.array([3,6,9])
d=np.array([[a,b,c],[a,b,c]])
print(d)
print(d.transpose())

[[[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]]
[[[1 1]
  [2 2]
  [3 3]]

 [[4 4]
  [5 5]
  [6 6]]

 [[7 7]
  [8 8]
  [9 9]]]


In [35]:
print(np.square(d))

[[[ 1 16 49]
  [ 4 25 64]
  [ 9 36 81]]

 [[ 1 16 49]
  [ 4 25 64]
  [ 9 36 81]]]


In [36]:
e=np.array([[c,b,a],[c,b,a]])
print(np.add(d,e))

[[[ 4 10 16]
  [ 4 10 16]
  [ 4 10 16]]

 [[ 4 10 16]
  [ 4 10 16]
  [ 4 10 16]]]


In [41]:
a=np.array([[1,3,2],[5,4,6]])
print(np.sort(a))
print(np.all(a>0))

[[1 2 3]
 [4 5 6]]
True
